Labjack1: #low speed signals
  ros__parameters:
    IPAddress: "192.168.1.21"
    SampleRate: 200.0 #Must include a decimal
    ScansPerRead: 20
    ainTopic: "/ain_1_fast"
    channelNames:
      - AIN0
      - AIN1
      - AIN2
      - AIN3
      - AIN4
      - AIN5
      - AIN6
      - AIN7
    channelScales: #Units = A*(Voltage)+B || Must include decimal 
      - 1.0            #AIN0
      - 1.0          #AIN1
      - 1.0    #AIN2
      - 1.0        #AIN3
      - 1.0             #AIN4
      - 1.0             #AIN5
      - 1.0             #AIN6
      - 1.0            #AIN7 
    channelOffsets: #Units = A*(Voltage)+B || Must include decimal 
      - 0.0              #AIN0
      - 0.0              #AIN1
      - 0.0         #AIN2
      - 0.0          #AIN3
      - 0.0               #AIN4
      - 0.0               #AIN5
      - 0.0               #AIN6
      - 0.0               #AIN7
    channelUnits:
      - V    #AIN0
      - V   #AIN1
      - V    #AIN2
      - V    #AIN3
      - V   #AIN4
      - V  #AIN5
      - V  #AIN6
      - V       #AIN7            
Labjack2: #high speed signals
  ros__parameters:
    IPAddress: "192.168.1.22"
    SampleRate: 25000.0 #Must include a decimal
    ScansPerRead: 1000
    ainTopic: "/ain_2_fast"
    channelNames:
      - AIN0
      - AIN1
      - AIN2
      - AIN3
      - AIN4
      - AIN5
      - AIN6
      - AIN7
    channelScales: #Units = A*(Voltage)+B || Must include decimal 
      - 1.0            #AIN0
      - 1.0          #AIN1
      - 1.0    #AIN2
      - 1.0        #AIN3
      - 1.0             #AIN4
      - 1.0             #AIN5
      - 1.0             #AIN6
      - 1.0            #AIN7 
    channelOffsets: #Units = A*(Voltage)+B || Must include decimal 
      - 0.0              #AIN0
      - 0.0              #AIN1
      - 0.0         #AIN2
      - 0.0          #AIN3
      - 0.0               #AIN4
      - 0.0               #AIN5
      - 0.0               #AIN6
      - 0.0               #AIN7
    channelUnits:
      - V    #AIN0
      - V   #AIN1
      - V    #AIN2
      - V    #AIN3
      - V   #AIN4
      - V  #AIN5
      - V  #AIN6
      - V       #AIN7            
BagRecorder:
  ros__parameters:
    dataFolder: "/media/m2/KINGSTON"
    fileDuration: 600 
    loggedTopics:
      - "*"
AwsS3:
  ros__parameters:
    bucketName: "m1-m2-comparison"
    filePrefix: "/m2_bag/"
M2Supervisor:
  ros__parameters:
    loggerPath: "/home/m2/Log"
    loggerLimitBytes: 1000000
    emailSendAddr: "youremailwithsmtpenabled@email.com"
    emailSendPwd: "passwordhere"
    emailGroup1:
      - "youremail@email.com"      
    emailGroup2:
      - "youremail2@email.com"
    analyzedTopics:
      - /ain_flap
      - /T8din
    topicErrorEmailSnooze: 60
Rosbridge:
  ros__parameters:
    delay_between_messages: 0.05
